### ISSUE TITLE
Can you share the Graph Neural Network part ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [chenhaoxing/M2L#2]
I have noticed that the `GraphFunc` imported [here](https://github.com/chenhaoxing/M2L/blob/2f4ab96386e21e303de762e4fb693ed01f9fd9b1/modules/query/mml.py#L7) is not provided in the `module.utils`.

**Comment by chenhaoxing** [comment]
Sorry for that, I've updated.

**Comment by MohamedAliRashad** [comment]
@chenhaoxing sorry for the many requests, but the weights link is not working.

**Comment by chenhaoxing** [comment]
> @chenhaoxing sorry for the many requests, but the weights link is not working.

Hi, I tried and it worked. Maybe you could train a backbone from scratch.

**Comment by MohamedAliRashad** [comment]
@chenhaoxing it provided me with this message ...
![Screenshot from 2022-02-23 10-55-54](https://user-images.githubusercontent.com/26205298/155287651-6538c2c6-36f9-47ed-a78f-90eed6160247.png)

I was planning to test the model for my use cases and then train a backbone from scratch (just to make sure it fits before investing the time)

**Comment by chenhaoxing** [comment]
> @chenhaoxing it provided me with this message ... ![Screenshot from 2022-02-23 10-55-54](https://user-images.githubusercontent.com/26205298/155287651-6538c2c6-36f9-47ed-a78f-90eed6160247.png)
> 
> I was planning to test the model for my use cases and then train a backbone from scratch (just to make sure it fits before investing the time)

Maybe you can find a solution at https://github.com/chenhaoxing/SSFormers. However, I tried and it worked.
